export default [
  {
    name: 'Tabbouleh',
    id: '1',
    description:
      'This is a modified version (or at least as close as I could come) to my favorite tabbouleh from a restaurant outside of Detroit.',
    ingredients: [
      '4 bunches curly-leaf parsley',
      '1/2 cucumber',
      '4-5 Roma tomatoes',
      '1 small white onion',
      '1/3 to 1/2 cup olive oil',
      '1/2 cup lemon juice',
      '1/2 to 2/3 tsp salt',
    ],
    steps: [
      'Rinse all vegetables; pay parsley dry or put it in a salad spinner.',
      'Remove as much parsley stem as possible then finely chop and add to large bowl.',
      'Chop tomatoes to desired size then place in strainer to remove juice; place in bowl.',
      'Chop onion and cucumber to desired size and place in bowl.',
      'Add olive oil, lemon juice and salt to bowl and mix thoroughly.',
    ],
    image: 'tabbouleh.png',
    course: 'salads',
    notes:
      'Feel free to adjust amounts of oil, lemon juice and salt to taste. Best to do after chilling tabbouleh in fridge for a few hours.',
  },
  {
    name: 'Caldo de Pollo',
    id: '2',
    description:
      'Based on one of my favorite menu items at a restaurant I will never go to again because of the horrid service.',
    ingredients: [
      '1 whole chicken (3-4 pounds), cut into large pieces',
      '8-10 cups water, depending on size of chicken',
      '2-3 tsp salt',
      '1/2 white onion',
      '4 garlic gloves, peeled & cut into large pieces',
      '3 celery branches, cut in half',
      '4 large carrots, cut in half',
      '2 cilantro branches',
      'Other vegetables as desired (potatoes, corn on the cob, cabbage, zucchini, chayotes) cut into large pieces.',
      'Avocado, cilantro, diced onion, lime, diced serrano or jalapeno peppers, cooked white rice, chipotle or adobo sauce to garnish.',
    ],
    steps: [
      'Place chicken, water and salt into a large stock pot at medium-high heat and bring to a boil. Once foam starts forming on the surface, skim & discard.',
      'After removing foam, add onion, garlic and celery. Partially cover the pot. Turn heat down and gently simmer for about 30 minutes. Do not boil.',
      'Add the carrots and cilantro. If using other vegetables, add them 15 minutes later. Check chicken for doneness and, once cooked, remove & set aside to cool.',
      'Keep simmering the broth for about 10 more minutes until carrots are completely cooked.',
      'When chicken pieces have cooled, shred or cut into small pieces. Dice carrots once cooked and set aside.',
      'Remove any remaining vegetables and set aside. Drain broth then return to pot, letting settle for 8-10 minutes. Use a large spoon to remove any fat that rises to the top.',
      'Cut up vegetables and return to pot along with chicken and heat through.',
      'Serve with garnishes.',
    ],
    image: 'caldo.png',
    course: 'soups',
    notes: '',
  },
  {
    name: 'Potatoes, Tomatoes & Meat',
    id: '3',
    description: 'THE Buda family recipe. The name says it all.',
    ingredients: [
      '1 good sized flank steak or top sirloin, cut into small pieces',
      '1 lb. pork steak or pork chops, cut into small pieces',
      '8-10 russet potatoes, thinly sliced',
      '1 28oz can whole tomatoes',
      '1 medium onion, chopped',
      'Salt & pepper to taste',
      'Butter, optional',
    ],
    steps: [
      'Combine meat, potatoes, onion in large stock pot, add enough water to cook potatoes, ,and mix thoroughly.',
      'Dot with butter is desired.',
      'Cover pot and bake at 350 degrees for 1 1/2 hours.',
      'Cut tomatoes into small pieces and add to pot.',
      'Heat through and serve.',
    ],
    image: 'potatoes-tomatoes-meat.png',
    course: 'main',
    notes: '',
  },
  {
    name: 'Cajun Blackening Dry Rub',
    id: '4',
    description: 'Great to use on white-fleshed fish, chicken breast, shrimp or corn on the cob.',
    ingredients: [
      '2 1/2 Tbsp. paprika',
      '1 Tbsp kosher salt',
      '1 1/2 tsp ground cumin',
      '1 1/2 tsp dried thyme',
      '1 tsp black pepper',
      '1/2 tsp garlic powder',
      '1/2 tsp ground red pepper',
    ],
    steps: ['Combine all ingredients. Store in an airtight container for up to 2 weeks.'],
    image: 'cajun-dry-rub.png',
    course: 'seasonings',
    notes: '',
  },
  {
    name: 'Wild Rice & Celery Root Soup',
    id: '5',
    description: 'Earthy flavor with the combination of celery root and wild rice.',
    ingredients: [
      '2 Tbsp oil',
      '1 Cup thinly sliced leek',
      '1/2 Cup finely chopped carrot',
      '2 Tbsp dry white wine',
      '3 Cups cubed peeled celery root (about 3/4 lb)',
      '3 Cups chicken broth',
      '1 Cup water',
      '1/2 tsp kosher salt',
      '1/2 tsp black pepper',
      '1 3/4 Cups cooked wild rice',
      '2 Tbsp minced fresh chives',
    ],
    steps: [
      'Heat oil in a large saucepan over medium heat. Add leek & carrot; cover & cook 5 minutes or until tender.',
      'Stir in wine, scraping pan to loosen browned bits.',
      'Add celery root, broth, 1 cup water, salt and pepper; bring to a boil. Cover & cook 10 muntes or until celery root is tender.',
      'Optional: Place 1 cup soup mixture in a blender; blend until smooth. Add pureed soup mixture back to saucepan.',
      'Add wild rice and cook 15 minutes.',
      'Sprinkle with chives.',
    ],
    image: 'wild-rice-celery-root-soup.png',
    course: 'soups',
    notes: '',
  },
  {
    name: "El Chucho's Tortilla Soup",
    id: '6',
    description:
      "A combination of multiple recipes that individually just didn't cut the mustard for me.",
    ingredients: [
      '4 6-inch corn tortillas, cut into 1/4 inch strips',
      '2 stemmed dried seeded pasilla (or 1 dried ancho) chiles',
      '12 oz skinless, boneless chicken breast, trimmed & diced',
      '1 Cup chopped onion',
      '1 Cup chopped green bell pepper',
      '1 jalapeno chile, diced (seeds optional)',
      '2 cloves garlic, minced',
      '3/4 tsp ground cumin',
      '3/4 tsp chili powder (or chipotle chili powder',
      '2 14-oz cans chicken broth',
      '1 14.5-oz can diced tomatoes, undrained',
      '1/4 tsp black pepper',
      '1/3 Cup chopped cilantro',
      'Avocado and crumbly queso fresco to garnish',
      'Lime wedges',
    ],
    steps: [
      'Heat oil over medium-high heat. Add tortillas and cook, stirring frequently, until brown and crisp, 3-4 minutes. Remove and drain on paper towel.',
      'Add dried chiles to pan with oil, and saute 60 seconds or until fragrant. Remove from pan and cool completely. Remove stems and chop chiles.',
      'Add chicken, onion, bell pepper, garlic and jalapeno to pan, adding more oil if needed. Cook 5 minutes or until chicken cooked through.',
      'Stir in cumin, chili powder, black pepper, broth & tomatoes. Bring to a boil, reduce heat, and simmer 10 minutes.',
      'Add cilantro and heat through.',
      'Ladle into bowls and garnish with tortilla strips, avocado, queso fresco and chopped chiles. Serve with a lime wedge.',
    ],
    image: 'tortilla-soup.png',
    course: 'soups',
    notes: '',
  },
  {
    name: "Mom's Apple Crisp",
    id: '7',
    description:
      "For real, Mom's actual apple crisp. This recipe was taught to middle school home economics kids for decades.",
    ingredients: [
      '4-6 medium apples',
      '1/2 Cup flour',
      '3/4 Cup oatmeal',
      '1/2 Cup butter (may reduce by 2 Tbsp)',
      '1/2 Cup brown sugar (may reduce by 2 Tbsp)',
      '1 Tsbp wheat germ (optional)',
      '1/2 tsp cinnamon',
    ],
    steps: [
      'Pre-heat oven to 350 degrees.',
      'Lightly grease a 9-inch round or square baking pan.',
      'Wash apples and peel skins. Slice into greased pan. Sprinkle with cinnamon',
      'Combine oatmeal, brown sugar, wheat germ and cinnamon. Mix butter in with your fingers. Mixture will be crumbly.',
      'Place mixture over the sliced apples.',
      'Place pan in center of oven. Bake 35-45 minutes, uncovered.',
    ],
    image: 'apple-crisp.png',
    course: 'desserts',
    notes: 'If doubling recipe, use a 9x13 inch pan.',
  },
  {
    name: 'Polynesian Flank Steak',
    id: '8',
    description: '',
    ingredients: [
      '1/3 Cup pineapple juice',
      '1/3 Cup low-sodium soy sauce',
      '1/2 Cup thinly sliced green onions',
      '1 Tbsp minced peeled fresh ginger',
      '1 Tbsp honey',
      '1 garlic clove, minced',
      '1 1/2 lbs flank steak',
      'Cooking spray',
    ],
    steps: [
      'Combine first 6 ingredients in a large zip-top plastic bag; add steak to bag. Seal and marinate in refrigerator 3 hours, turning once.',
      'Prepare grill.',
      'Remove steak from bag, reserving marinade. Place steak on grill rack coated with cooking spray; grill 20 minutes or until desired degree of doneness, turning and basting frequently with the reserved marinade.',
      'Let stand 10 minutes before cutting diagonally across the grain into thin slices.',
    ],
    image: 'polynesian-flank-steak.png',
    course: 'main',
    notes: '',
  },
  {
    name: 'Arctic Char',
    id: '9',
    description: '',
    ingredients: [
      '3 tbsp extra-virgin olive oil, divided',
      '4 6-oz arctic char filets',
      '3/4 tsp coarse salt, divided',
      '1/2 tsp black pepper, divided',
      '4 garlic cloves, halved',
      '3 pints multicolored cherry tomatoes',
      '1/4 cpu thinly sliced fresh basil',
      '2 shallots, thinly sliced',
    ],
    steps: [
      'Preheat oven to 400 degrees.',
      'Heat a large ovenproof skillet over high heat. Add 1 tbsp oil to pan & swirl to coat.',
      'Sprinkle filets with 1/2 tsp salt and 1/4 tsp pepper. Add filets, flesh side down, to pan and saute for 2 minutes. Place pan in oven cook at 400 for 3 minutes or until desire degree of doneness.',
      'Heat a large cast-iron skillet over medium heat. Add remaining 2 btsp oil to pan & swirl to coat. Add garlic, and cook 2 minutes or until lightly browned, stirring occasionally. Increase heat to medium-high. Add tomatoes to pan, saute for 2 minutes or until skins blister, stirring frequently.',
      'Remove pan from heat. Sprinkle tomato mixture with remaining salt & pepper, basil and shallots; toss to combine. Serve with fish.',
    ],
    image: 'arctic-char.png',
    course: 'main',
    notes: '',
  },
  {
    name: 'Banana Chip Bars',
    id: '10',
    description: '',
    ingredients: [
      '2 cups flour',
      '2 tsp baking powder',
      '1/2 tsp salt (optional)',
      '2/3 cup butter',
      '2/3 cup white sugar',
      '2/3 cup brown sugar',
      '1 tsp vanilla',
      '1 egg',
      '1 cup mashed bananas (about 2)',
      '6 oz chocolate chips',
    ],
    steps: [
      'Sift together the flour, baking powder & salt.',
      'Cream butter and sugars. Add vanilla, egg and bananas.',
      'Stir in chocolate chips.',
      'Spread in greased 9x13 pan.',
      'Bake at 350 degrees for 20-25 minutes.',
    ],
    image: 'banana-chip-bars.png',
    course: 'desserts',
    notes: '',
  },
  {
    name: 'Roasted Garlic & Kale Soup',
    id: '11',
    description: '',
    ingredients: [
      '1 head garlic',
      '1 cup macaroni or any small, tube-shaped pasta',
      '1 tbsp olive oil',
      '2 large leeks',
      '1 tbsp fresh rosemary, diced',
      '8 cups kale, washed & chopped',
      '4 cups sweet potato, peeled & chopped into 1/2-inch pieces',
      '7 cups fat-free chicken broth',
      '1 tsp dried basil',
      '2 cans cannellini beans, rinsed & drained',
      'Salt & pepper to taste',
    ],
    steps: [
      'Preheat oven to 425',
      'Wrap garlic head in tinfoil & bake for 40 minutes or until soft. Remove from oven and cool. Remove cloves from papery shell and set aside.',
      'Cook pasted in salted water until al dente. Drain & set aside.',
      'Pour oil into a large soup pan over medium-high heat. Add leeks, rosemary & roasted garlic, and saute, stirring constantly until leeks are transparent, about 5 minutes.',
      'Add kale & sweet potato, continue to stir for 5 minutes.',
      'Add chicken broth and basil, return to gentle boil, reduce heat and simmer until potato is soft but firm, approximately 15 minutes.',
      'Add beans, pasta, salt & pepper to taste, and heat through for 5 minutes. Serve hot.',
    ],
    image: 'roasted-garlic-kale.png',
    course: 'soups',
    notes: '',
  },
  {
    name: 'Beany Salad',
    id: '12',
    description: '',
    ingredients: [
      '1/2 cup pearl barley',
      '1/2 cup long-grain brown rice',
      '1 cup canned black beans, drained',
      '1 cup canned kidney beans, drained',
      '1 cup cooked corn kernels',
      '1/2 cup chopped green onions',
      '1 red pepper',
      '1/4 cup chopped cilantro',
      '1/4 cup red wine vinegar',
      '1 clove minced garlic',
      '1 tsp chili powder',
      '1/2 tsp salt',
      '1/4 tsp black pepper',
      '1/4 tsp red pepper flakes',
      '1/2 cup olive oil',
    ],
    steps: [
      'Bring 2 cups water to boil. Stir in barley & reduce to medium heat. Cover & simmer for 40-45 minutes. Cool.',
      'In another pan boil 1 1/2 cup water to boil. Add rice and reduce to low. Cover & simmer for 20 minutes. Cool.',
      'In a large bowl, combine barley, rice, beans, corn, onions, pepper & cilantro.',
      'Wisk together remaining ingredients and mix into barley mixture.',
    ],
    image: 'no-photo.png',
    course: 'sides',
    notes: '',
  },
  {
    name: 'Beef & Barley Stew',
    id: '13',
    description: '',
    ingredients: [
      'Cooking spray',
      '2 cups chopped onion (about 1 large)',
      '1 lb chuck steak, trimmed & cut into 1/2-inch cubes',
      '1 1/2 cups chopped peeled carrot (about 4)',
      '1 cup chopped celery (about 4 stalks)',
      '5 garlic cloves, minced',
      '1 cup uncooked pearl barley',
      '5 cups fat-free, less-sodium beef broth',
      '2 cups water',
      '1/2 cup no-salt-added tomato puree',
      '1/2 tsp kosher salt',
      '1/4 tsp ground black pepper',
      '2 bay leaves',
    ],
    steps: [
      'Heat a large Dutch oven over medium heat. Coat pan with cooking spray. Add chopped onion and beef to pan. Cook 10 minutse or until onion is tender & beef is browned, stirring occasionally.',
      'Add carrot & celery to pan. Cook 5 minutes, stirring occasionally.',
      'Stir in garlic. Cook 30 seconds.',
      'Stir in barley & remaining ingredients and bring to a boil. Cover, reduce heat, and simmer 40 minutes or until the barley is done and vegetables are tender. Discard bay leaves.',
    ],
    image: 'beef-barley-stew.png',
    course: 'soups',
    notes: '',
  },
  {
    name: 'Black Bean Tostadas',
    id: '14',
    description: '',
    ingredients: [
      '1/2 cup chopped avocado',
      '1/2 cup chopped seeded tomato',
      '1/4 cup thinly sliced green onions',
      '2 Tbsp & 2 tsp fresh lime juice, separated',
      '1/4 tsp salt',
      '2 Tbsp water',
      '1/2 tsp ground cumin',
      '1/8 tsp salt',
      '1/8 tsp ground red pepper',
      '1 15-oz can black beans, rinsed & drained',
      '4 8-inch flour tortillas',
      '1 cup shredded, roasted, skinless chicken breast',
      '3/4 cup preshredded Monterey Jack cheese',
      '1 cup shredded iceberg lettuce',
      '1/2 cup fat-free sour cream',
    ],
    steps: [
      'Preheat broiler.',
      'To prepare salsa, combine avocado, tomato, green onions, 2 tsp lime juice and salt in a small bowl. Toss gently & set aside.',
      'Combine water, remaining lime juice, cumin, salt, red pepper and beans in a blender. Process until smooth.',
      'Place tortillas on a baking sheet and spread about 1/4 cup bean mixture evenly over each tortilla. Top each evenly with 1/4 cup chicken and 3 Tbsp cheese. Broil 2 minutes or until cheese melts and tortilla edges are just beginning to brown.',
      'Top each tortilla with 1/4 cup lettuce, 1/4 cup salsa and 2 Tbsp sour cream. Cut each tortilla into 4 wedges.',
    ],
    image: 'black-bean-tostadas.png',
    course: 'main',
    notes: '',
  },
  {
    name: 'Cajun Spice Mix',
    id: '15',
    description: '',
    ingredients: [
      '3 tbsp paprika',
      '2 tbsp ground red pepper',
      '2 tbsp dried thyme',
      '2 tbsp dried oregano',
      '2 tbsp onion powder',
      '2 tbsp garlic powder',
      '1 tbsp kosher salt',
      '1 tbsp black pepper',
      '1 tbsp sugar',
    ],
    steps: ['Combine all ingredients.'],
    image: 'no-photo.png',
    course: 'seasonings',
    notes: '',
  },
  {
    name: 'Breakfast Hash',
    id: '16',
    description: 'Great for a Sunday home brunch!',
    ingredients: [
      '1 1/2 tbsp olive oil',
      '1 large redskin potato, cut into 1/4 inch cubes',
      'Salt & pepper to taste',
      '1/4 medium white onion, chopped',
      '1 serrano pepper, chopped & seeded',
      '2 cloves garlic, minced',
      '2-3 eggs',
      '6-10 cherry tomatoes',
      '1 medium avocado, sliced',
    ],
    steps: [
      'Add oil to a large pan and heat on medium-high. Add potato, salt & pepper to pan and cook until potato is mostly cooked.',
      'Add onion and pepper to pan and continue cooking until onion starts to brown.',
      'Stir garlic into pan and continue cooking for 2-3 minutes, until garlic fragrant.',
      'Remove potato mixture from pan and put onto plate.',
      'In same pan, put in eggs and cook until desired doneness. Remove from pan and put on top of potato mixture.',
      'Cut tomatoes in half and sprinkle with salt. Place cut-side down in pan and cook 4-5 minutes or unti tomatoes start to blacken. Remove from pan and place on plate.',
      'Ring plate with sliced avocado. Add desired garnishes (cilantro, queso fresco, hot sauce).',
    ],
    image: 'no-photo.png',
    course: 'breakfasts',
    notes:
      'For a lower carb version, substitute cauliflower for potato. And for additional spice, add red chili flakes to the potato, salt & pepper.',
  },
  {
    name: 'Cilantro-Lime Chicken with Avocado Salsa',
    id: '17',
    description: '',
    ingredients: [
      '2 tbsp minced fresh cilantro',
      '2 1/2 tbsp fresh lime juice',
      '1 1/2 tbsp olive oil',
      '4 6-oz skinless, boneless chicken breast halves',
      '1/2 tsp salt, divided',
      'Cooking spray',
      '1 cup chopped plum tomato (about 2)',
      '2 tbsp finely chopped onion',
      '2 tsp fresh lime juice',
      '1/4 tsp black pepper',
      '1 avocado, peeled & finely chopped',
    ],
    steps: [
      'Combine first 4 ingredients in a large bowl; toss and let stand 3 minutes. Remove chicken from marinade; discard marinade. Sprinkle chicken evenly with 1/4 tsp salt.',
      'Heat a grill pan over medium-high heat. Coat pan with cooking spray. Add chicken to pan and cook 6 minutes on each side or until done.',
      'To prepare salsa, combine tomato & next 4 ingredients (thru pepper) & remaining 1/4 tsp salt in a medium bowl. Add avocado; stir gently to combine. Serve salsa over chicken.',
    ],
    image: 'cilantro-chicken.png',
    course: 'main',
    notes: '',
  },
  {
    name: 'Chicken Green Chili with White Beans',
    id: '18',
    description: '',
    ingredients: [
      '6 Anaheim chiles',
      '1 tbsp olive oil',
      '3 chicken leg quarters, skinned (about 1 3/4 lbs)',
      '1 3/4 cups chopped onion',
      '4 garlic cloves, minced',
      '4 cups fat-free, low-sodium chicken broth',
      '2 cups water, divided',
      '1 1/2 tsp ground cumin',
      '1 (15.5-oz) can cannellini beans or other white beans, rinsed & drained',
      '3 tbsp all-purpose flour',
      '1 tsp salt',
      '3 tbsp reduced-fat sour cream',
      '6 lime slices',
    ],
    steps: [
      'Cut chiles in half; discard seeds & membranes. Place halves, skin sides up, on a foil-lined baking sheet; flatten with hand. Broil 5 minutes or until blackened. Place in a heavy-duty zip-top plastic bag; seal. Let stand 15 minutes. Peel chiles; discard skins. Chop chiles',
      'Heat oil in a large Dutch oven over medium-high heat. Add chicken; cook 4 minutes on each side or until browned. Remove chicken from pan. Add onion and garlic, and saute 6 minutes on each side or until browned, stirring frequently. Return chicken to pan. Add broth, 1 1/2 cups water, cumin; bring to a simmer. Cook 20 minutes or until chicken is done.',
      'Remove chicken; cool slightly. Remove chicken from bones; cut meat into bite-size pieces. Add chicken to pan; stire in chopped chiles & beans.',
      'Combine 1/2 cup water and flour, stirring with a whisk. Stir into chicken mixture. Bring to a simmer; cook 15 minutes. Stir in salt.',
      'Spoon about 1 1/2 cups soup into each of 6 bowls; top each with 1 1/2 tsp sour cream. Serve with lime slices',
    ],
    image: 'no-photo.png',
    course: 'soups',
    notes: '',
  },
  {
    name: 'Simple Clam Chowder',
    id: '19',
    description: '',
    ingredients: [
      '2 bacon slices',
      '2 cups chopped onion',
      '1 1/4 cups chopped celery',
      '1/2 tsp salt',
      '1/2 tsp dried thyme',
      '2 garlic cloves, minced',
      '6 (6 1/2 oz) cans chopped clams, undrained',
      '5 cups diced peeled baking potato (about 1 lb)',
      '4 (8-oz) bottles clam juice',
      '1 bay leaf',
      '3 cups fat-free milk',
      '1/2 cup all-purpose flour',
    ],
    steps: [
      'Cook bacon in a large Dutch oven over medium heat until crisp. Remove from pan, reserving 1 tsp drippings in pan. Crumble & set aside.',
      'Add onion, celery, salt, thyme & garlic to drippings in pan; cook 4 minutes or until vegetables are tender.',
      'Drain clams, reserving liquid. Add clam liquid, potato, clam juice and bay leaf to pan; bring to a boil. Reduce heat and simmer 15 minutes or until potato is tender. Discard bay leaf.',
      'Combine milk & flour, stirring with a whisk until smooth. Add flour mixture to pan; bring to a boil. Cook 12 minutes oruntil thick, stirring constantly.',
      'Add clams; cook 2 minutes. Sprinkle with bacon.',
    ],
    image: 'clam-chowder.png',
    course: 'soups',
    notes: '',
  },
  {
    name: 'Irish Colcannon & Thyme Leaf Soup',
    id: '20',
    description: '',
    ingredients: [
      '2 tbsp butter, divided',
      '2 1/2 cups diced peeled baking potato',
      '1 cup diced onion',
      '1/2 tsp salt, divided',
      '1/2 tsp black pepper, divided',
      '3 cups fat-free, less-sodium chicken broth',
      '2 cups plus 3 tbsp water',
      '8 cups thinly sliced savoy cabbage (about 1 lb)',
      '1 tbsp chopped fresh thyme leaves',
    ],
    steps: [
      'Melt 1 tbsp butter in a large saucepan over medium heat. Add potato, onion, 1/4 tsp salt & 1/4 tsp pepper. Cover & cook 6 minutes.',
      'Add broth and 2 cups water; bring to a boil. Cook 10 minutes or until potato is tender.',
      'Combine 3 tbsp water and remaining 1 tbsp butter in a large Dutch oven; bring to a simmer. Add cabbage and thyme. Cover and cook 5 minutes, stirring occasionally. Remove from heat; stir in remaining 1/4 tsp salt & 1/4 tsp pepper.',
      'Place 1/2 of potato mixture in blender. Remove center piece of blender lid to allow steam to escape. Place lid on blender and cover with paper towel to avoid splatters. Blend until smooth. Pour into large bowl. Repeat process with remaining potato mixture.',
      'Add potato mixture to cabbage mixture; cook over medium-low heat until thoroughly heated.',
    ],
    image: 'colcannon-thyme-soup.png',
    course: 'soups',
    notes: '',
  },
  {
    name: 'Corn & Fingerling Potato Chowder',
    id: '21',
    description: '',
    ingredients: [
      '2 sliced applewood smoked bacon',
      '1 3/4 cups diced onion',
      '3 1/2 cups fresh corn kernels (about 7 ears)',
      '1 tsp chopped fresh thyme',
      '2 garlic cloves, minced',
      '2 cups fat-free, less-sodium chicken broth',
      '1/2 cup 2% reduced-fat milk',
      '1/2 cup half-and-half',
      '8 oz (1/4-inch thick) round fingerling potato slices',
      '1/4 tsp salt',
      '1/4 tsp black pepper',
      'Thyme sprigs (optional)',
    ],
    steps: [
      'Cook bacon in a large Dutch oven over medium heat until crisp. Remove bacon from pan & crumble.',
      'Add onion to drippings in pan; cook 8 minutes or until tender, stirring occasionally.',
      'Add corn, chopped thyme & garlic to pan; cook 30 seconds, stirring constantly.',
      'Stir in broth, milk, half-and-half & potatoes; bring to a simmer. Cover & cook 30 minutes or until potatoes are tender, stirring occasionally.',
      'Transfer 2 cups potato mixture to a blender. Remove center piece of blender lid to allow steam to escape. Place lid on blender and cover with paper towel to avoid splatters. Blend until smooth.',
      'Return pureed mixture to pan. Stir in salt & pepper.',
      'Sprinkle with crumbled bacon. Serve with thyme sprigs if desired.',
    ],
    image: 'corn-fingerling-chowder.png',
    course: 'soups',
    notes: '',
  },
  {
    name: 'Creamy Parmesan Orzo',
    id: '22',
    description: '',
    ingredients: [
      '1 tbsp butter',
      '1 cup orzo',
      '1 1/4 cups fat-free, less-sodium chicken broth',
      '1 1/4 cups water',
      '1/4 cup grated fresh Parmesan cheese',
      '3 tbsp chopped fresh basil',
      '1/4 tsp salt',
      '1/4 tsp black pepper',
      '4 tsp pine nuts, toasted',
    ],
    steps: [
      'Heat butter in a medium saucepan over medium heat. Add orzo & cook 3 minutes, stirring constantly.',
      'Stir in broth & water; bring to a boil. Reduce heat and simmer until liquid is absorbed & orzo is done (about 15 minutes). Remove from heat.',
      'Stir in cheese, basil, salt & pepper. Sprinkle with pine nuts.',
    ],
    image: 'parmesan-orzo.png',
    course: 'sides',
    notes: '',
  },
  {
    name: 'Chicken Enchilada Soup',
    id: '23',
    description: '',
    ingredients: [
      '2 tsp olive oil',
      '1/2 cup onion, chopped',
      '3 cloves garlic, minced',
      '3 cups low sodium fat-free chicken broth',
      '8 oz can tomato sauce',
      '1-2 tsp chipotle chili in adobo sauce (or more to taste)',
      '1/4 cup chopped cilantro (plus more for garnish)',
      ' 15 oz can black beans, rinsed and drained',
      '14.5 oz can petite diced tomatoes',
      '2 cups frozen corn',
      '1 tsp cumin',
      '1/2 tsp dried oregano',
      '2, 8 oz skinless chicken breasts (16 oz total)',
      '1/4 cup chopped scallions, for topping',
      '3/4 cup shredded reduced fat cheddar cheese',
      'fat free sour cream (optional)',
    ],
    steps: [
      'Heat oil in a saucepan over medium-low heat. Add onion and garlic and sauté until soft, 3-4 minutes. Slowly add the chicken broth, tomato sauce and chipotle adobo sauce and bring to a boil. Add cilantro and remove from heat. Pour into crock pot.',
      'To the crockpot, add drained beans, diced tomatoes, corn, cumin, oregano and stir. Add the chicken breasts; cover and cook on low heat for 4-6 hours.',
      'Remove chicken and shred with two forks. Add chicken back into the soup, adjust salt and cumin to taste. Serve in bowls and top with fat free sour cream, cheese, scallions and cilantro. You can also top with avocado or crushed tortilla chips. Enjoy!',
    ],
    image: 'chicken-enchilada-soup.png',
    course: 'crockpot',
    notes: '',
  },
  {
    name: 'Chipotle Chicken Zucchini Soup',
    id: '24',
    description: '',
    ingredients: [
      '16 oz boneless, skinless chicken breasts',
      '1/2 teaspoon kosher salt',
      'fresh black pepper, to taste',
      '1 teaspoon olive oil',
      '1/2 cup chopped onion',
      '3 cloves minced garlic',
      '4 cups reduced sodium chicken broth',
      '8 oz can tomato sauce',
      '1/2 tablespoon chipotle chile in adobo, chopped',
      '1 teaspoon dried oregano',
      '1/4 teaspoon cumin',
      '2 bay leaves',
      '1/4 cup chopped cilantro',
      '1 (7 ounce) zucchini',
      '1 medium (5 oz) avocado, pitted and sliced',
      '2 ounces crumbled queso fresco or queso blanco (omit for Paleo)',
    ],
    steps: [
      'Season chicken with salt and pepper and place in the slow cooker.',
      'Heat a medium nonstick skillet over medium heat, add oil, onion and garlic and saute until soft, 3 to 4 minutes. Transfer to the slow cooker with chicken broth, tomato sauce, chipotle, cumin, oregano, half of the cilantro and bay leaves. Cover and cook low 4 to 6 hours.',
      'Meanwhile spiralize the zucchini using a spiralizer with the thinnest noodle setting. Cut the zucchini into 6-inch strips.',
      'Discard the bay leaves and remove the chicken, shred with 2 forks and place back in the slow cooker along with the zucchini and cook on high until the zucchini is tender crisp, about 5 minutes. To serve, ladle into bowls and serve topped with sliced avocado and remaining cilantro.',
    ],
    image: 'chicken-zucchini-soup.png',
    course: 'crockpot',
    notes: '',
  },
  {
    name: 'Moroccan Chickpea Turkey Stew',
    id: '25',
    description: '',
    ingredients: [
      'cooking spray',
      '1.3 lb package 93% lean ground turkey',
      '1 tbsp extra virgin olive oil, light',
      '1 yellow onion, chopped',
      '2 garlic cloves, chopped',
      '3 tbsp poblano pepper, chopped',
      '1 cup diced carrots',
      '1 cup diced celery',
      '28 oz can petite diced tomatoes ',
      '2 (15 oz) cans chick peas, drained',
      '2 cups low sodium, 99% fat free chicken broth',
      '2 tsp turmeric',
      '2 tsp paprika',
      '1 tsp coriander',
      '2 bay leaves',
      '1/2 tsp crushed red pepper flakes',
      '2 tsp coarse salt',
      '2 tbsp fresh Italian parsley or spearmint, chopped',
    ],
    steps: [
      'Spray a large nonstick skillet with cooking spray and over medium high heat cook ground turkey for 10-12 minutes.  Break up the ground meat and mix so meat cooks evenly; place in the slow cooker.',
      'To the skillet add the olive oil, onions, pepper, carrots, and celery and sauté until soft, about 8 minutes.  Add garlic and sauté for another 2 minutes. Transfer to slow cooker along with diced tomatoes, chick peas, spices, broth and gently mix well.  Cover and cook on LOW heat 6 to 8 hours.  Remove bay leaves and serve; garnish with fresh herbs.',
    ],
    image: 'moroccan-chickpea-turkey.png',
    course: 'crockpot',
    notes: '',
  },
  {
    name: 'Picante Chicken Black Bean',
    id: '26',
    description: '',
    ingredients: [
      '2 (15 oz) cans black beans, rinsed and drained',
      '3 1/2 cups low sodium chicken broth',
      '2 (10 oz) cans Rotel tomatoes with green chilies',
      '1 red bell pepper, minced',
      '4 oz can diced green chiles',
      '1 tbsp ground cumin',
      '1 tsp ancho chile powder',
      '1 tsp garlic powder',
      '1 tsp onion powder',
      '1/4 tsp oregano',
      '16 oz (2) skinless chicken breast',
      '1/2 cup chopped cilantro, divided',
      '2 medium scallions, diced',
      'cut limes, for serving ',
      '1 medium haas avocado, sliced',
      'sour cream, for serving (optional)',
    ],
    steps: [
      'Take one can of beans and place in the blender along with 2 cups of the chicken broth; puree then add to your slow cooker. Add the remainder of the beans and chicken broth into the slow cooker along with tomatoes, bell pepper, diced green chiles, cumin, chile powder, garlic powder, onion powder, oregano, chicken breast, and 1/4 cup of the cilantro. Set slow cooker to HIGH 4 hours or LOW 6 to 8 hours.',
      "After it's done, remove chicken and shred with 2 forks. Place back into the slow cooker and add fresh scallions, remainder cilantro and adjust salt and cumin, to taste.",
    ],
    image: 'picante-chicken-black-bean.png',
    course: 'crockpot',
    notes: '',
  },
  {
    name: 'Pork & Tomato Soup',
    id: '27',
    description: '',
    ingredients: [
      '2 lbs boneless country pork ribs, cut into 1 inch pieces',
      '1 Tbsp olive oil',
      '1 Tbsp chopped garlic',
      '½ cup chopped onion',
      '½ cup dry white wine',
      '1 cup chicken stock',
      '2 cups fresh tomatoes, chopped',
      '1 cup water',
      '2 Tbsp fresh oregano, chopped',
      '2 cups finely chopped cauliflower rice',
      'salt and pepper to taste',
    ],
    steps: [
      'Heat the olive oil in a heavy saucepan. Season the pork (or other meat) generously with salt and pepper. Brown the meat on all sides for several minutes or until golden. Add the garlic and onions and cook for 2 minutes. Ad the white wine, chicken stock, fresh tomatoes and water and bring to a boil. Pour into a slow cooker and cook on high for 4 hours or until the meat is tender and falling apart. In the last 15-20 minutes of cooking, stir in the cauliflower and fresh oregano. ',
    ],
    image: 'tomato-pork-soup.png',
    course: 'crockpot',
    notes: '',
  },
  {
    name: 'Fiery Flank Steak with Tomato Jam',
    id: '28',
    description: '',
    ingredients: [
      '6 large ripe tomatoes, cored & cut in half crosswise (about 4 lbs)',
      '1/3 cup sugar',
      '1/3 cup grated onion',
      '5 garlic cloves, minced, divided',
      '4 jalapeno peppes, minced, divided',
      '1/4 cup chopped fresh cilantro',
      '1/3 cup & 3 tbsp lime juice, divided',
      '3/4 tsp salt, divided',
      '1 tbsp grated lime rind',
      '2 tsp olive oil',
      '2 lb. flank steak, trimmed',
      'Cooking spray',
      'Lemon slices, optional',
    ],
    steps: [
      'To prepare jam, grate tomatoes, flesh side down, over a large bowl to form 5 1/2 cups pulp; discard skins.',
      'Combine pulp, sugar, onion, 3 garlic cloves and 2 jalapenos in a medium saucepan; bring to a boil.',
      'Reduce heat and simmer until reduced to 2 1/4 cups (about 20 minutes), stirring occasionally. Cool to room temperature. Stir in cilantro, 3 tbsp lime juice and 1/4 tsp salt.',
      'To prepare steak, combine rind, 1/3 cup juice, oil, 2 jalapenos and 2 garlic cloves in a large zip-top plastic bag. Add steak & seal. Marinate in refrigerator 8 hours or overnight, turning bad occasionally.',
      'Prepare grill.',
      'Remove steak from bag; discard marinade. Sprinkle both sides of steak evenly with 1/2 tsp salt. Place steak on a grill rack coated with cooking spray; grill 3 minutes on each side or until desired degree of doneness. Let stand 5 minutes. Cut steak diagonally across the grain into thin slices. Serve with jam. Garnish with lemon slices, if desired.',
    ],
    image: 'fiery-flank-steak.png',
    course: 'main',
    notes: '',
  },
  {
    name: 'Garlic Fries',
    id: '29',
    description: '',
    ingredients: [
      '4 tsp canola oil',
      '3/4 tsp salt',
      '3 lbs peeled baking potatoes, cut into 1/4-inch thick strips',
      'Cooking spray',
      '2 tbsp butter',
      '8 garlic cloves, minced (about 5 tsp)',
      '2 tbsp finely chopped fresh parsley',
      '2 tbsp freshly grated Parmesan cheese',
    ],
    steps: [
      'Preheat oven to 400.',
      'Combine first 3 ingredients in a large zip-top plastic bag, tossing to coat. Arrange potatoes in a single layer on a baking sheet coated with cooking spray. Bake at 400 for 50 minutes or until potatoes are tender and golden brown, turning after 20 minutes.',
      'Place butter and garlic in a large nonstick skillet, and cook over low heat 2 minutes, stirring constantly. Add potatoes, parsley and cheese to pan; toss to coat.',
    ],
    image: 'garlic-fries.png',
    course: 'sides',
    notes: '',
  },
  {
    name: 'Garlic Roasted Potatoes with Herbs',
    id: '30',
    description: '',
    ingredients: [
      '2 tbsp chopped garlic',
      '1 tbsp olive oil',
      '1 1/2 lbs quartered Yukon gold or red potatoes (about 4 cups)',
      'Cooking spray',
      '1/2 tsp sea salt',
      '1/4 tsp black pepper',
      '1/4 cup chopped fresh flat-leaf parsley',
      '1/2 tsp grated lemon rind',
    ],
    steps: [
      'Preheat oven to 475 degrees.',
      'Combine garlic and oil in a small saucepan over medium heat. Cook 2 minutes or until golde, stirring frequently. Remove garlic with a slotted spoon; set aside.',
      'Drizzle remaining oil evenly over potatoes in a large bowl, tossing well to coat. Arrange potatoes in a single layer on a baking sheet coated with cooking spray, and sprinkle with salt & pepper. Bake at 475 for 30 minutes or until potatoes are golden.',
      'Combine reserved garlic, parsley and lemon rind in a small bowl; sprinkle mixture evenly over potatoes.',
    ],
    image: 'garlic-potatoes-herbs.png',
    course: 'sides',
    notes: '',
  },
  {
    name: 'Gazpacho',
    id: '31',
    description: '',
    ingredients: [
      '1 green bell pepper, seeded & roughly chopped',
      '1 red bell pepper, seeded & roughly chopped',
      '1/2 cucumber, roughly chopped',
      '1 onion, roughly chopped',
      '1 fresh red chili, seeded & roughly chopped',
      '3 cups roughly chopped ripe plum tomatoes',
      '3 3/4 cups passata (strained pureed tomatoes) or tomato juice',
      '2 tbsp red wine vinegar',
      '2 tbsp olive oil',
      '1 tbsp caster sugar',
      'Salt & pepper',
      'crushed ice, to garnish (optional)',
    ],
    steps: [
      'Reserve a small piece of the peppers, cucumber and onion. Finely chop these & set aside as a garnish.',
      'Process all the remaining ingredients, except the ice, in a blender or food processor until smooth.',
      'Press the soup through a strainer into a clean glass bowl, pushing it through with a spoon to extract the maximum amount of flavor.',
      'Adjust the seasoning and chili. Serve sprinkled with the reserved chopped peppers, cucumber & onion. Add crushed ice to garnish.',
    ],
    image: 'gazpacho.png',
    course: 'soups',
    notes: '',
  },
  {
    name: 'Greek-Style Potato, Zucchini & Bean Stew',
    id: '32',
    description: '',
    ingredients: [
      '1 1/2 tbsp extra virgin olive oil',
      '3 cups chopped onion',
      '1 cup (3/4 inch) cubed peeled baking potato',
      '1/2 cup water',
      '3 1/2 cups (1/2 inch thick) slices zucchini',
      '2 1/2 cups (3 inch) cut green beans (about 1/2 lb)',
      '2 28-oz cans diced tomatoes, undrained',
      '1 15.5-oz can Great Northern beans, rinsed & drained',
      '1/4 cup chopped fresh flat-leaf parsley',
      '2 tsp chopped fresh dill',
      '1/2 tsp dried oregano',
      '1/4 tsp black pepper',
      '3/4 cup crumbled feta cheese',
    ],
    steps: [
      'Heat oil in a Dutch oven over medium-high heat. Add onion & saute 5 minutes or until lightly browned. Add potato & water; bring to a boil. Cover, reduce heat and cook 5 minutes.',
      'Stir in zucchini and the next 3 ingredients (through Great Northern beans). Cover and cook 35 minutes or until vegetables are tender.',
      'Stir in parsley & next 3 ingredients (through pepper). Serve with cheese.',
    ],
    image: 'no-photo.png',
    course: 'soups',
    notes: '',
  },
  {
    name: 'Grilled Salmon with Roasted Corn Relish',
    id: '33',
    description: '',
    ingredients: [
      '4 Anaheim chiles',
      'Cooking Spray',
      '2 shucked ears corn',
      '1 cup diced tomato',
      '1/4 cup chopped fresh cilantro',
      '6 tbsp fresh lime juice',
      '1 tsp salt, divided',
      '1/2 tsp black pepper, divided',
      '1 tsp ground cumin',
      '4 6-oz skinless salmon fillets',
    ],
    steps: [
      'Prepare grill.',
      'Place chiles on gril rack coated with cooking spray. Grill 5 minutes on each side or until blackened. Place chiles in a heavy-duty zip-top plastic bag, seal. Let stand 5 minutes. Peel chiles and cut in half lengthwise. Discard seeds and membranes. Cut chiles into 1/4-inch strips.',
      'Place corn on grill rack coated with cooking spray. Grill 10 minutes or until lightly browned, turning occasionally. Cool slightly. Cut kernels from cobs.',
      'Combine chiles, corn, tomato, cilantro and juice; toss gently. Add 1/2 tsp salt and 1/4 tsp black pepper.',
      'Combine remaining 1/2 tsp salt, 1/4 tsp pepper and cumin, stirring well. Rub spice mixture evenly over both sides of salmon. Place salmon on grill rack coated with cooking spray. Grill 4 minutes on each side or until fish flakes easily when tested with a fork or until desired degree of doneness. Serve with relish.',
    ],
    image: 'salmon-corn-salsa.png',
    course: 'main',
    notes: '',
  },
  {
    name: 'Herb-Grilled Trout',
    id: '34',
    description: '',
    ingredients: [
      '1/4 cup dry white wine',
      '1 tbsp olive oil',
      '4 8-oz dressed rainbow trout',
      '1/4 tsp salt',
      '1/8 tsp black pepper',
      '1/2 cup thinly sliced green onions',
      '2 tbsp chopped fresh tarragon',
      '2 tbsp chopped fresh basil',
      '1 tbsp chopped fresh dill',
      'Cooking spray',
      '4 lemon wedges',
    ],
    steps: [
      'Prepare grill or broiler.',
      'Combine the wine and oil; brush inside and outside of fish. Sprinkle the insides evenly with salt, pepper, onions and fresh herbs.',
      'Place the fish, skin side down, on grill rack or broiler pan coated with cooking spray, and cook for 5 minutes or until the fish flakes easily when tested with a fork. Serve with lemon wedges.',
    ],
    image: 'herb-grilled-trout.png',
    course: 'main',
    notes:
      "If you don't want to use wine, it turns out fine without it. Also, instead of cutting the lemon into wedges, I often slice the lemon really thing and place the slices inside the fish and then cook it.",
  },
  {
    name: 'Herb Roasted Pork Tenderloin',
    id: '35',
    description: '',
    ingredients: [
      '1 1/2 tbsp butter, softened',
      '1 1/4 tsp kosher salt',
      '1/2 tsp dried sage',
      '1/2 tsp dried thyme',
      '1/4 tsp dried oregano',
      '2 1-lb pork tenderloins, trimmed',
      'Cooking spray',
    ],
    steps: [
      'Preheat oven to 475 degrees.',
      'Combine the first 5 ingredients in a small bowl. Rub butter mixture over pork.',
      'Place pork on a broiler pan coated with cooking spray. Bake at 475 for 17 minutes or until a thermometer reads 155 degrees (slightly pink). Let stand 5 minutes; slice thin.',
    ],
    image: 'herb-pork-tenderloin.png',
    course: 'main',
    notes: 'Olive or other vegetable oil can replace the butter.',
  },
  {
    name: 'Lentil Soup',
    id: '36',
    description: '',
    ingredients: [
      '2 tbsp olive oil',
      '2 1/2 cups chopped Rio or other sweet onion',
      '1 cup chopped celery',
      '1 cup chopped carrot',
      '1/2 tsp dried thyme',
      '4 garlic cloves, minced',
      '1 bay leaf',
      '1 1/2 cups dried petite green lentils',
      '4 cups fat-free, less-sodium chicken broth',
      '1 cup water',
      '1 14.5-oz can petite-cut diced tomatoes, drained',
      '2 tbsp fresh lemon juice',
      '1/2 tsp salt',
      '3/4 tsp black pepper, divided',
    ],
    steps: [
      'Heat oil in a large saucepan over medium-high heat. Add onion and next 5 ingredients (through bay leaf) to pan; saute 12 minutes.',
      'Add lentils; cook for 2 minutes, stirring constantly.',
      'Stir in broth, 1 cup water and tomatoes; bring to a boil. Cover, reduce heat, and simmer 40 minutes or until lentils are very tender. Remove from heat; let stand for 5 minutes. Discard bay leaf.',
      'Place 3 cups lentil mixture in a blender. Remove center piece of blender lid to allow steam to escape; secure blender lid and place a paper towel over lide to avoid splatters. Blend until smooth and return pureed mixture to pan.',
      'Stir in juice, salt and 1/4 tsp pepper. Sprinkle with remaining pepper.',
    ],
    image: 'lentil-soup.png',
    course: 'soups',
    notes: '',
  },
  {
    name: 'Mussels Marinara',
    id: '37',
    description: '',
    ingredients: [
      '1 tbsp olive oil',
      '1 cup finely chopped onion',
      '3 garlic cloves, minced',
      '2 cups chopped tomato',
      '1/2 cup dry white wine',
      '1/3 cup chopped fresh flat-leaf parsley',
      '2 tbsp chopped fresh basil',
      '1/2 tsp salt',
      '1/2 tsp black pepper',
      '1/4 tsp crushed red pepper',
      '2 bay leaves',
      '5 lbs fresh mussels, scrubbed & debearded (about 100 mussels)',
      '5 cups hot cooked linguine (about 10 oz uncooked pasta)',
      'Basil sprigs (optional)',
    ],
    steps: [
      'Heat oil in a large stockpot over medium-high heat. Add onion and garlic; saute 3 minutes.',
      'Add tomato and next 7 ingredients (through bay leaves). Cook over medium heat 5 minutes.',
      'Add mussels; cover and cook 10 minutes or until mussels open. Discard bay leaves & any unopened shells. Remove mussels with a slotted spoon.',
      'Serve mussels and tomato mixture over linguine. Garnish with basil sprigs, if desired.',
    ],
    image: 'mussels-marinara.png',
    course: 'main',
    notes: '',
  },
  {
    name: 'New Orleans-Style Shrimp',
    id: '38',
    description: '',
    ingredients: [
      '3 tbsp Worcestershire sauce',
      '2 tbsp fresh lemon juice',
      '1 tbsp butter, melted',
      '2 tsp chopped fresh rosemary',
      '2 tsp chopped garlic',
      '1/2 tsp dried thyme',
      '1/2 tsp hot pepper sauce (such as Tabasco)',
      '1/4 tsp freshly ground black pepper',
      '1/4 tsp ground red pepper',
      '2 lbs unpeeled large shrimp',
      '2 lemons, sliced into 1/4-inch slices',
      '4 tsp butter, divided',
    ],
    steps: [
      'Combine first 11 ingredients in a large bowl; toss well. Cover and marinate in refrigerator 30 minutes.',
      'Preheat oven to 425 degrees.',
      'Fold 4 (16x12 inch) sheets of heavy-duty aluminum foil in half crosswise. Open foil. Remove shrimp mixture from bowl; reserve marinade. Place about 2 1/4 cups shrimp mixture on half of each foil sheet. Drizzle remaining marinade evenly over shrimp. Top each serving with 1 tsp butter. Fold foil over shrimp and tighly seal edges.',
      'Place packets on a baking sheet and bake and 425 for 20 minutes. Let stand 10 minutes. Place on plates. Unfold packets carefully; peel shrimp and serve immediately.',
    ],
    image: 'nola-shrimp.png',
    course: 'main',
    notes: '',
  },
  {
    name: 'Orzo Salad',
    id: '39',
    description: '',
    ingredients: [
      '2 cup orzo pasta, cooked al dente (yields 3 cups)',
      '6 oz feta cheese, cut into 1/4-inch cubes',
      '2 large tomatoes, diced',
      '5 scallions, diced',
      '3 tbsp fresh dill, chopped fine',
      '3 oz fresh lemon juice',
      '6 oz olive oil',
      '1 tsp fresh cracked black pepper',
      '1 tsp minced garlic',
      'Salt to taste',
    ],
    steps: [
      'Prepare orzo, let cool. Add feta, tomatoes, scallions & dill; toss well.',
      'Combine remaining ingredients and whisk together. Pour over orzo mixture. Refrigerate until cold.',
    ],
    image: 'no-photo.png',
    course: 'sides',
    notes:
      'To kick it up a few notches, you can also add fresh spinach, olives, shrimp or grilled chicken.',
  },
  {
    name: 'Peasant Stew',
    id: '40',
    description: '',
    ingredients: [
      '1 tsp ground cumin',
      '1/4 tsp salt',
      '1/4 tsp black pepper',
      '6 chicken thighs (about 1 1/2 lbs), skinned',
      '1 cup chopped onion',
      '1 (14.5-oz) can Mexican-style stewed tomatoes, with jalapeno peppers and spices, undrained',
      '1 (4.5-oz) can chopped green chiles, undrained',
      '1 (15-oz) can pinto beans, rinsed and drained',
      '1 (15-oz) can kidney beans, rinsed and drained',
      '1/4 cup minced fresh cilantro',
      '1/4 cup reduced-fat sour cream',
    ],
    steps: [
      'Combine cumin, salt and pepper; sprinkle over chicken.',
      'Place chicken in an electric slow cooker; stir in onion, tomatoes and chiles. Cover and cook on high setting for 3 hours.',
      'Stir in beans. Cover and cook on high for 1 hour.',
      'Place 1 chicken thigh in each of 6 soup bowls. Ladle 1 1/4 cups stew into each bowl. Top with cilantro and sour cream.',
    ],
    image: 'no-photo.png',
    course: 'crockpot',
    notes: '',
  },
  {
    name: 'Popsoon',
    id: '41',
    description:
      "Grandma Buda's original recipe. Although nobody will ever be able to make it quite like she did.",
    ingredients: [
      '2 eggs',
      '2 tsp salt, divided',
      '3 scoops & 3 tbsp flour',
      '6-7 potatoes, chopped',
      '1 onion, chopped',
      '3 tbsp butter',
      'Milk (optional)',
      'Black pepper (optional)',
    ],
    steps: [
      'Mix eggs, 1 tsp salt and 3 scoops flour. Knead mixture and chop into small pieces.',
      'Place potatoes in large pot and cover with water until potatoes are covered by 3-4 inches of water.',
      'Add onion and 1 tsp salt to pot; boil until potatoes soft.',
      'Add noodles and continue boiling until noodles soft.',
      'In a separate small pan, melt butter over low heat and add in 3-4 tbsp flour, mixing constantly until a smooth roux is formed. Stir into soup pot and heat through. Serve in soup bowls and add a little milk and black pepper if desired.',
    ],
    image: 'no-photo.png',
    course: 'soups',
    notes: '',
  },
  {
    name: 'Potato-Leek Soup',
    id: '42',
    description: '',
    ingredients: [
      '1 tbsp butter',
      '3 cups thinly sliced leek (about 3 medium)',
      '6 cups cubed peeled Yukon gold potatoes (about 2 1/4 lbs)',
      '2 cups water',
      '1/2 tsp salt',
      '2 (14-oz) cans organic vegetable broth',
      'Thyme sprigs',
      '1/4 tsp black pepper',
    ],
    steps: [
      'Melt butter in a Dutch oven over medium heat. Add leek; cook 10 minutes or until tender, stirring occasionally (do not brown).',
      'Add potatoes, water, salt, broth and 2 thyme sprigs. Bring to a boil; reduce heat and simmer, uncovered, for 20 minutes or until potatoes are very tender.',
      'Remove pan from heat. Discard thyme sprigs. Partially mash potatoes with a potato masher. Sprinkle with black pepper. Garnish with thyme sprigs, if desired.',
    ],
    image: 'potato-leek-soup.png',
    course: 'soups',
    notes: '',
  },
  {
    name: 'Red Beans & Rice',
    id: '43',
    description: '',
    ingredients: [
      '3 cups water',
      '1 cup dried red kidney beans',
      '1 cup chopped onion',
      '1 cup chopped green bell pepper',
      '3/4 cup chopped celery',
      '1 tsp dried thyme',
      '1 tsp paprika',
      '3/4 tsp ground red pepper',
      '1/2 tsp black pepper',
      '1/2 (14-oz) package turkey, pork and beef smoked sausage, thinly sliced',
      '1 bay leaf',
      '5 garlic cloves, minced',
      '1/2 tsp salt',
      '3 cups cooked long-grain rice',
      '1/4 cup chopped green onions',
    ],
    steps: [
      'Combine first 12 ingredients in an electric slow cooker. Cover with lid and cook on high for 5 hours. Discard bay leaf; stir in salt. Serve over rice; sprinkle servings evenly with green onions.',
    ],
    image: 'red-beans-rice.png',
    course: 'crockpot',
    notes: '',
  },
  {
    name: 'Roast Leg of Lamb with Chile-Garlic Sauce',
    id: '44',
    description: '',
    ingredients: [
      '1 (1-lb) boneless leg of lamb, trimmed',
      '3/4 tsp and 1/8 tsp salt, divided',
      '1/2 tsp ground black pepper',
      'Cooking spray',
      '1 tbsp sambal oelek (ground fresh chile paste)',
      '1/2 tsp ground cumin',
      '1/4 tsp ground coriander',
      '3 garlic cloves, minced',
      '2 tbsp olive oil',
    ],
    steps: [
      'Preheat oven to 425 degrees.',
      'To prepare lamb, sprinkle evenly wth 3/4 tsp salt and pepper. Place lamb on a broiler pan coated with cooking spray and bake at 425 for 20 minutes or until a thermometer reads 120 degrees in the thickest part of the meat. Place lamb on a cutting board; let stand at room temperature 10 minutes before slicing.',
      'To prepare sauce, combine sambal oelek and next 4 ingredients (through garlic) with a mortar and pestle; grind into a fine paste. Slowly drizzle oil into sambal mixture, stirring until thoroughly combined. Serve sauce with lamb.',
    ],
    image: 'lamb-chile-sauce.png',
    course: 'main',
    notes: '',
  },
  {
    name: 'Roasted Cauliflower with Fresh Herbs & Parmesan',
    id: '45',
    description: '',
    ingredients: [
      '12 cups cauliflower, coarsley chopped (about 2 heads)',
      '1 1/2 tbsp olive oil',
      '1 tbsp chopped fresh parsley',
      '2 tsp chopped fresh thyme',
      '2 tsp chopped fresh tarragon',
      '3 garlic cloves, minced',
      '1/4 cup (1 oz) grated fresh Parmesan cheese',
      '2 tbsp fresh lemon juice',
      '1/2 tsp salt',
      '1/4 tsp pepper',
    ],
    steps: [
      'Preheat oven to 450 degrees.',
      'Place cauliflower in a large roasting pan or jelly-roll pan. Drizzle with oil; toss well to coat. Bake at 450 for 20 minutes or until tender and browned, stirring every 5 minutes. Sprinkle with parsley, thyme, tarragon and garlic. Bake 5 minutes. Combine cauliflower mixture, cheese, and remaining ingredients in a large bowl; toss well to combine.',
    ],
    image: 'roasted-cauliflower.png',
    course: 'sides',
    notes: '',
  },
  {
    name: 'Seared Tuna with Chickpea Salad',
    id: '46',
    description: '',
    ingredients: [
      '1/2 cup olive oil, divided',
      '1/2 tsp Spanish paprika',
      '1/2 tsp salt',
      '1/8 tsp black pepper',
      '2 8-oz tuna fillets',
      '1 (6-oz) jar marinated artichoke hearts',
      '1 (15.5-oz) can cooked chickpeas, drained',
      '1 1/2 tbsp chopped fresh Italian or flat-leaf parsley',
      '1 1/2 tsp grated lemon zest',
      '3 tbsp fresh lemon juice',
    ],
    steps: [
      'Whisk together 1/4 cup olive oil and next 3 ingredients in a small bowl.',
      'Coat tuna with oil mixture, and sear in hot (slightly smoking) cast-iron skillet for 1 1/2 to 2 minutes per side or until rare to medium-rare.',
      'Combine remaining ingredients in a medium bowl; cover and chill.',
      'Serve tuna over chickpea salad.',
    ],
    image: 'no-photo.png',
    course: 'main',
    notes: '',
  },
  {
    name: 'Shrimp Cakes with Corn & Avocado Salsa',
    id: '47',
    description: '',
    ingredients: [
      '1 lb medium shrimp, peeled & deveined',
      'Cooking spray',
      '1 cup finely chopped red bell pepper',
      '1 garlic clove, minced',
      '1/4 cup thinly sliced green onions',
      '3 tbsp reduced-fat mayonnaise',
      '2 tbsp fresh lime juice, divided',
      '1 1/2 tsp hot sauce',
      '1/2 tsp sugar',
      '1/2 tsp salt, divided',
      '1 large egg',
      '1/2 cup finely chopped fresh cilantro, divided',
      '3/4 cup panko (Japanese breadcrumbs), divided',
      '1 cup frozen white corn, thawed',
      '3/4 cup diced, peeled avocado',
      '3 tbsp finely chopped red onion',
      '2 tbsp finely chopped poblano pepper',
    ],
    steps: [
      'To prepare cakes, place shrimp in a food processor; pulse 10 times or until finely chopped. Set aside.',
      'Heat a large nonstick skillet over medium heat. Coat pan with cooking spray. Add bell pepper to pan; saute 3 minutes. Add garlic; saute for 1 minute. Remove from heat. Place bell peper mixture in a large bowl.',
      'Add shrimp, green onions, mayonnaise, 1 tbsp lime juice, hot sauce, sugar, 1/4 tsp salt and egg to bowl, stirring well. Stir in half the cilantro and 1/4 cup panko.',
      'Divide shrimp mixture into 10 equal portions, shaping each into a 1/2-inch thick patty. Dredge both sides of patties in remaining 1/2 cup panko. Chill at least one hour.',
      'Heat pan over medium-high heat. Coat pan with cooking spray. Add 5 cakes to pan; cook 4 minutes on each side or until browned. Remove from pan; cover and keep warm. Repeat with remaining cakes.',
      'To prepare salsa, combine remaining ingredients and stir gently to mix. Serve immediately with shrimp cakes.',
    ],
    image: 'shrimp-cakes.png',
    course: 'main',
    notes: 'I often substitute a can of salmon for the shrimp.',
  },
  {
    name: 'Taco Seasoning',
    id: '48',
    description: '',
    ingredients: [
      '1 tbsp chili powder',
      '1/4 tsp garlic powder',
      '1/4 tsp onion powder',
      '1/4 tsp crushed red pepper flakes',
      '1/4 tsp dried oregano',
      '1/2 tsp paprika',
      '1 1/2 tsp ground cumin',
      '1 tsp sea salt',
      '1 tsp black pepper',
    ],
    steps: ['Combine all ingredients.'],
    image: 'no-photo.png',
    course: 'seasonings',
    notes:
      'This is a great seasoning mix to add to a crockpot filled with chicken breast and enough chicken broth to cover the chicken. Cook on low about 8 hours then shred the chicken, return to the pot and stir it all together.',
  },
  {
    name: 'Thai Chicken & Coconut Soup',
    id: '49',
    description: '',
    ingredients: [
      '1 lb boneless, skinless chicken breasts (about 3), cut into 2 1/2 by 1/4 inch strips',
      '3 tbsp Asian fish sauce (nam pla or nuoc mam)',
      '1 1/2 tbsp lime juice',
      '1 quart plus 3/4 cup canned low-sodium chicken broth or homemade stock',
      '3 stalks lemongrass, bottom third only, peeled, smashed, and cut into 2-inch pieces; or three 3-inch-by-1/4-inch strips lemon zest',
      '1 1-inch piece peeled fresh ginger, cut into thirds',
      '1/2 cup long-grain rice',
      '1 3/4 cups unsweetened coconut milk (15-oz can)',
      '2 fresh red chiles or jalapeno peppers, seeds & ribs removed, cut crosswise into thin slices',
      '3 tbsp chopped cilantro',
    ],
    steps: [
      'In a medium glass dish or stainless steel pan, combine the chicken strips with the fish sauce and lime juice. Set aside.',
      'In a large saucepan, bring the broth, lemongrass, and ginger to a simmer. Add the rice; simmer until rice is almost done, about 15 minutes.',
      'Add the coconut milk and bring back to a simmer. Stir in the chicken and marinade and cook until the chicken is just done, about 2 minutes. Stir in the chiles and cilantro.',
    ],
    image: 'thai-coconut-soup.png',
    course: 'soups',
    notes: '',
  },
  {
    name: 'Sesame-Crusted Tuna with Wasabi-Ponzu Sauce',
    id: '50',
    description: '',
    ingredients: [
      '1 tbsp chopped green onions',
      '2 tbsp low-sodium soy sauce',
      '2 tbsp fresh orange juice',
      '1 tbsp rice vinegar',
      '1 tsp brown sugar',
      '1 tsp grated lemon rind',
      '2 tsp fresh lemon juice',
      '2 tsp honey',
      '1 1/4 tsp prepared wasabi paste',
      '1 tsp grated peeled fresh ginger',
      '2 tsp vegetable oil',
      '4 (6-oz) tuna steaks (about 3/4 inch thick)',
      '1/4 tsp salt',
      '3 tbsp sesame seeds',
      '2 tbsp black sesame seeds',
      'Sliced green onions (optional)',
    ],
    steps: [
      'Combine first 10 ingredients, stirring with a whisk.',
      'Heat oil in a large nonstick skillet over medium-high heat. Sprinkle tuna with salt. Combine sesame seeds in a shallow dish. Dredge tuna in sesame seeds. Add tuna to pan; cook 3 minutes on each side or until desired degree of doneness. Garnish with green onions, if desired. Serve tuna with sauce.',
    ],
    image: 'sesame-tuna-ponzu.png',
    course: 'main',
    notes: '',
  },
  {
    name: 'Vegan Chili',
    id: '51',
    description: '',
    ingredients: [
      '1 1/2 tbsp vegetable oil',
      '1 onion, chopped',
      '1 stalk celery, sliced',
      '28 oz diced tomatoes',
      '2 cups vegetable broth',
      '1-2 tbsp molasses',
      '2 tsp cumin',
      '1 1/2 tsp sage',
      '1/2 tsp black pepper',
      '8 cups beans (Great Northern, kidney, chili), drained',
    ],
    steps: [
      'Heat oil to a large pot over medium heat. Add onion to pot and cook until just tender. Add the celery and continue cooking until celery softens.',
      'Add rest of ingredients except beans; simmmer for 20 minutes.',
      'Add beans; simmer for 15 more minutes.',
    ],
    image: 'no-photo.png',
    course: 'soups',
    notes:
      'For a non-vegan version, use chicken broth instead of vegetable broth, and replace 4 cups of the beans with 1/2 pound lean ground turkey and 1/2 pound ground sausage.',
  },
  {
    name: 'White Chili with Chicken',
    id: '52',
    description: '',
    ingredients: [
      '1 medium onion, chopped',
      '1 jalapeno pepper, seeded and chopped',
      '2 garlic cloves, minced',
      '1 tbsp vegetable oil',
      '4 cups chicken broth',
      '2 15.5-oz cans great northern beans, rinsed & drained',
      '2 tbsp minced fresh parsley',
      '1 tbsp lime juice',
      '1 to 1-1/4 tsp ground cumin',
      '2 tbsp cornstarch',
      '1/4 cup water',
      '2 cups cubed cooked chicken',
      '1 cup shredded carrots',
    ],
    steps: [
      'In a large saucepan, cook onion, jalapeno and garlic in oil until tender.',
      'Stir in broth, beans, parsley, lime juice and cumin; bring to a boil. Reduce heat; cover and simmer for 1o minutes, stirring occasionally.',
      'Combine cornstarch and water until smooth; stir into chili.',
      'Add chicken and carrots. Bring to a boil; cook and stir for 2 minutes or until thickened.',
    ],
    image: 'no-photo.png',
    course: 'soups',
    notes: '',
  },
  {
    name: 'Salad Nicoise with Seared Tuna',
    id: '53',
    description: '',
    ingredients: [
      'Romaine or other salad greens',
      'Tomatoes, cut into medium sized slices',
      'Hard-boiled eggs, sliced',
      'Red onion, cut into thin slices',
      'Kalamata or Nicoise olives, pitted',
      'Green beans',
      'Redskin potatoes, cut into large chunks',
      'Capers',
      'Sushi-grade tuna steaks',
      '1/2 cup olive oil',
      '2-3 tbsp brown mustard',
      '2 garlic cloves, minced',
      'Salt & pepper',
    ],
    steps: [
      'In a steamer pan, steam green beans until just starting to get tender. Set aside.',
      'In a large pot, place potatoes and cover with water. Bring to a boil and cook until potatoes can be pierced easily with a fork. Remove from pot and set aside.',
      'Place green beans and potatoes in fridge until cold.',
      'To prepare tuna, pat dry with paper towel. Rub lightly with olive oil and sprinkle with salt & pepper. Place in a grill pan on high heat and cook each side until just seared. Remove from pan, let cool slightly, then cut into thin slices.',
      'For dressing, conbine oil, mustard, garlic, and salt & pepper to taste and whisk together.',
      'Place lettuce in a salad bowl. Top with desired amounts of tomato, onion, green beans, potato, eggs, olives and capers. Add sliced tuna and drizzle with dressing.',
    ],
    image: 'tuna-nicoise.png',
    course: 'salads',
    notes:
      'I have no idea the amounts I typically use when I make this. I prep all the ingredients and then just throw whatever I want into a bowl.',
  },
  {
    name: 'Turkey Chili',
    id: '54',
    description: '',
    ingredients: [
      '2 lbs. of ground beef or turkey',
      '1 onion, diced',
      '3 cloves of garlic, minced',
      '1 red and 1 green bell pepper, both diced',
      '1 cup of carrots, finely diced',
      '1 cup of celery, diced',
      '1 jalapeno, minced',
      '(1) 28-ounce can of crushed or stewed tomatoes',
      '(1) 14-ounce can of diced tomatoes',
      '(1) 15-ounce can of tomato sauce',
      '3 Tbsp. of chili powder',
      '1 Tbsp. of oregano',
      '1 Tbsp. of basil',
      '2 tsp. of cumin',
      '1 tsp. of salt',
      '1 tsp. pepper',
      '1 tsp. onion powder',
      '1/2 tsp cayenne',
      'About 4 strips of cooked bacon, crumbled (optional)',
      '1 or 2 avocados, diced (optional)',
    ],
    steps: [
      'Sauté onions and garlic together in a large saucepan over medium heat.',
      'Add in ground beef (or turkey) to the saucepan and cook just until browned. Drain excess fat.',
      'Transfer the cooked onions, garlic and meat to your crockpot/slow-cooker.',
      'Add all the above vegetables and spices (except bacon & avocados) to the crockpot.',
      'Give the pot a good stir.',
      'Set crockpot to low, cover, and slow cook for about 6 hours.',
      'Spoon into individual bowls. Garnish with crumbled bacon and avocado slices.',
    ],
    image: 'crockpot-turkey-chili.png',
    course: 'crockpot',
    notes: '',
  },
  {
    name: 'Bok Choy & Mushrooms',
    id: '55',
    description: '',
    ingredients: [
      '2 cups bok choy, stems & leaves, chopped',
      '1 cup chopped mushrooms (any kind)',
      '1 Tbsp garlic powder',
      '1/2 tsp ground black pepper',
      '1 Tbsp sesame oil',
      '1.5 Tbsp olive oil',
      '1/2 tsp salt',
      '1/4 tsp ground chili flakes, optional',
    ],
    steps: [
      'Heat olive oil in a large saucepan over medium heat.',
      'Add bok choy stems to saucepan.',
      'Once stems start becoming tender, add remaining ingredients except for sesame oil. Continue cooking 5 minutes or until mushrooms become tender and bok choy leaves begin to wilt.',
      'Add sesame oil and cook, stirring constantly for 1 minute. Remove from heat and serve immediately.',
    ],
    image: 'no-photo.png',
    course: 'sides',
    notes: '',
  },
  {
    name: 'Curried Chicken & Butternut Squash',
    id: '56',
    description: '',
    ingredients: [
      '1 medium butternut squash, peeled, seeded & diced',
      '1 1/2 lbs. chicken breast, cubed',
      '2 Tbsp curry powder',
      '1 tsp fresh grated ginger',
      '1 garlic clove, minced',
      '3 Tbsp tomato paste',
      '1 can cocunut milk, full fat',
      'Juice of 1 medium lime',
      '2 Tsbp cilantro, for garnish',
      '1/8 tsp salt, to taste',
      '1/8 tsp black pepper, to taste',
    ],
    steps: [
      'Put all of the ingredients except salt, pepper, lime juice, cilantro into a crockpot. Stir to make sure all ingredients are coated, and add water if necessary to make sure everything is covered.',
      'Cover & cook on low for 6-8 hours. Before serving, stir in lime juice, season with salt & pepper, and garnish with cilantro.',
    ],
    image: 'no-photo.png',
    course: 'crockpot',
    notes: '',
  },
  {
    name: 'Baked Eggplant',
    id: '57',
    description: '',
    ingredients: [
      '1 eggplant, cut into 1/2 inch slices',
      'Olive oil',
      'Oregano, thyme, garlic powder, salt & pepper to taste',
    ],
    steps: [
      'Preheat oven to 425 degrees.',
      'Rub each side of eggplant slices with enough olive oil to coat.',
      'Sprinkle each side of eggplant slices with oregano, thyme, garlic powder, salt & pepper to taste.',
      'Place eggplant slices on a baking sheet and place in oven for 25 minutes, flipping once.',
    ],
    image: 'eggplant.jpg',
    course: 'sides',
    notes:
      'Eggplant soaks up oil extremely fast. To reduce this, you can salt the slices first and let them sit for about 30 minutes.',
  },
  {
    name: 'Chicken & Cauliflower Stew',
    id: '58',
    description: '',
    ingredients: [
      '2 Tbsp olive oil',
      '1 onion, diced',
      '2 cloves garlic, minced',
      '2 cups spinach, chopped',
      '2 cups cauliflower florets',
      '6 cups chicken broth',
      '1 can coconut milk',
      '1 can sliced mushrooms',
      '2 Tbsp capers',
      '3 chicken breasts',
      'Sea salt & fresh ground pepper, to taste',
      'Red pepper flakes, to taste',
    ],
    steps: [
      'Heat the oil in a large stockpot or Dutch oven. Add the onions and cook until soft. Add garlic and cook for another minute.',
      'Stir in spinach & cauliflower and add broth and red pepper flakes. Bring to a boil and add chicken breasts. Reduce to a simmer and simmer until chicken is cooked, about 20 minutes.',
      'Remove chicken from pot and shred. Lightly mash cauliflower then add chicken back to pot.',
      'Stir in coconut milk, mushrooms & capers, and simmer until heated through before serving.',
    ],
    image: 'no-photo.png',
    course: 'soups',
    notes: '',
  },
  {
    name: 'Beef Stew',
    id: '59',
    description: 'A hearty, easy to make beef stew.',
    ingredients: [
      '1 medium onion, chopped',
      '2 cups baby carrots',
      '2 cups sliced celery',
      '1 poblano pepper, diced',
      '1 jalapeno pepper, diced',
      '1 pound red potatoes, unpeeled, cubed',
      '2 pounds beef stew meat, cut into bite-size chunks',
      '2 tsp each of dried thyme leaves, oregano, sage, rosemary, basil',
      '2 bay leafs',
      '2 (14.5 oz) cans diced tomatoes, undrained',
      '1 6-oz can tomato paste',
      '2 cans of tomato paste worth of water',
      '2 (6 oz) cans mushrooms)',
      'red chili flakes (optional) for a little kick',
      'salt to taste',
    ],
    steps: ['Toss everything into a crockpot and cook on low 8-10 hours or until meat is tender.'],
    image: 'no-photo.png',
    course: 'crockpot',
    notes: '',
  },
  {
    name: 'Massaged Kale Salad',
    id: '60',
    description: 'Simple kale salad',
    ingredients: [
      '2 bunches kale',
      '1/2 cup grated Parmesan cheese',
      '1/3 cup extra-virgin olive oil',
      '1/4 cup lemon juice',
      '3 garlic cloves, minced',
      '1 tbsp soy sauce',
      '1/2 tsp ground pepper',
      '1/2 tsp salt',
    ],
    steps: [
      'Strip leaves from the stems (discard stems). Wash and dry the leaves. Tear the leaves into small pieces and place in a large bowl.',
      'Add Parmesan, oil, lemon juice, garlic, soy sauce, pepper and salt.',
      'With clean hands, firmly massage and crush the greens to work in the flavoring. Stop when the volume of greens is reduced by about half. The greens should look a little darker and somewhat shiny. Taste and adjust seasoning with more Parmesan, lemon juice, garlic, soy sauce and/or pepper, if desired.',
    ],
    image: 'no-photo.png',
    course: 'salads',
    notes: '',
  },
  {
    name: 'Pan-Grilled Steak with Garlic and Herbs',
    id: '61',
    description: 'Seared and baked steak with great seasoning mix',
    ingredients: [
      '2 boneless strip steaks (1-1 1/2 inches thick',
      '1/4 cup minced fresh rosemary, thyme',
      '3 garlic cloves',
      '1 tbsp smoked paprika',
      '1/2-1 tsp cayenne powder',
      '1/2 tsp white pepper',
      '2-4 tsp oil',
    ],
    steps: [
      'Let steak reach room temperature while preheating oven to 425 degrees.',
      'Rub steaks with oil then season with remaining ingredients.',
      'Place oven-save pan on burner turned to medium-high heat.',
      'Sear steaks in pan for 2-3 minutes per side then place in oven.',
      'Check steaks for doneness (140-160 degrees in center depending on desired doneness).',
      'Remove from oven and let sit for a few minutes before serving.',
    ],
    image: 'no-photo.png',
    course: 'main',
    notes: '',
  },
  {
    name: 'Baked Buffalo Wings',
    id: '62',
    description: "Paleo-friendly version of everyone's favorite appetizer!",
    ingredients: [
      '2 1/2 pounds chicken wings',
      '2 Tbsp avocado oil',
      '1 tsp salt',
      '2 tsp garlic powder',
      '1/4 cup ghee or clarified butter',
      '1/2 cup hot sauce',
    ],
    steps: [
      'Preheat oven to 400 degrees and line a tray with foil. Place a wire rack on top of the tray.',
      'Place wings in a large bowl and pat dry with paper towel.',
      'Add oil, salt and garlic powder and toss until evenly coated.',
      'Place wings on the wire rack, skin side up.',
      'Bake for 40 minutes.',
      'Prepare the sauce during the last 10 minutes of cooking: whisk the ghee (or clarified butter) and hot sauce in a sauce pan until combined.',
      'Once wings are done, coat them in the sauce and place back on the wire rack. Bake for 5 more minutes and repeat the process one more time.',
    ],
    image: 'no-photo.png',
    course: 'appetizers',
    notes: 'Makes about 26-28 wings.',
  },
  {
    name: 'Sheet Pan Chicken with Sourdough & Bacon',
    id: '63',
    description:
      'Roast chicken on a smoky, peppery bed of potatoes, red onion and crisp, fat-basted croutons.',
    ingredients: [
      '1/2 lb. sourdough boule, cut or torn into 2-inch pieces',
      '1/2 lb. slab bacon, cut into 1-by-1/2 inch lardons',
      '1 large baking potato scrubbed, halved crosswide and cut into 3/4 inch wedges',
      '1 large red onion, cut into 1 inch wedges',
      '2 Tbsp cold unsalted butter, diced',
      '4 oregano sprigs',
      '1/2 tsp crushed red pepper',
      '1/4 cup olive oil',
      'Kosher salt & black pepper',
      '6 whole chicken legs',
    ],
    steps: [
      'Preheat oven to 400 degrees. On a large rimmed baking sheet, toss the bread, bacon, potato, onion, butter, oregano and crushed red pepper with the olive oil and season generously with salt and black pepper. Spread into an even layer. Season chicken with salt and black pepper and arrange on the bread mixture.',
      'Roast chicken and bread mixture for about 45 minutes, until the bread is crisp and a thermometer in the chicken registers 160 degrees.',
    ],
    image: 'no-photo.png',
    course: 'main',
    notes: '',
  },
  {
    name: 'Steak and Brassicas with Red Wine Sauce',
    id: '64',
    description: 'Pan sauce pulls together the steak and roasted vegetables.',
    ingredients: [
      '1 1/2 lbs. multicolored brassicas, such as baby cauliflower and Romanesco, cut into 1 inch florets',
      '4 thyme sprigs',
      '5 Tbsp olive oil',
      'Kosher salt and black pepper',
      '7 Tbsp cold, unsalted butter, diced',
      '2 lb. hanger steaks',
      '2 small shallots, minced',
      '2 garlic cloves, minced',
      '1/2 cup red wine',
      '1/2 cup chicken stock',
    ],
    steps: [
      'Preheat oven to 425 degrees. On a large rimmed baking sheet, toss the brassicas and thyme with 1/2 cup olive oil and season generously with salt and pepper. Spread in a layer and scatter 2 Tbsp butter on top. Roast for 20-25 minutes until golden and tender.',
      'Meanwhile, in a large cast iron skillet, heat the remaining 1 Tbsp oil. Season steak with salt and pepper. Add to skillet and cook over moderately high heat, turning often, until a thermoteter reads 120 degrees, 15-20 minutes. Transfer to a carving board and let rest for 10 minutes. Do not wipe out the skillet.',
      'In the same skillet, cook the shallot and garlic over moderate heat, stirring, until softened, 2 minutes. Add the wine and cook, scraping up any browned bits, until almost evaporated, 3 minutes. Add the stock and cook until slightly reduced, 2 minutes. Remove from heat and gradually whisk in the remaining 5 Tbsp butter until emulsified; season with salt and pepper. Carve the steaks against the grain. Serve with the brassicas and sauce.',
    ],
    image: 'no-photo.png',
    course: 'main',
    notes: '',
  },
  {
    name: 'Vegetable Soup',
    id: '65',
    description: 'Easy to make slow cooker vegetable soup.',
    ingredients: [
      '4 cups vegetable (or chicken) broth',
      '3 cups diced tomatoes (or 1 28oz can)',
      '1 sweet onion, diced',
      '3 celery stalks, chopped',
      '3-4 carrots, chopped',
      '1 sweet potato, peeled and chopped',
      '1 cup green beans, halved',
      '1 bell pepper, chopped (I substitute a poblano)',
      '3 cloves garlic, minced',
      '2 tsp dried parsley',
      '1 bay leaf',
      'salt and black pepper to taste',
      'dash of red chili flakes (optional)',
    ],
    steps: [
      'Add all ingredients to slow cooker and cook on high for 3-5 hours until vegetables soft.',
    ],
    image: 'no-photo.png',
    course: 'crockpot',
    notes: 'I add 2-3 chicken breasts and shred them once the soup is done cooking.',
  },
  {
    name: 'Crockpot Brisket',
    id: '66',
    description: 'Simple brisket in a crockpot recipe. Set it and forget it.',
    ingredients: [
      "1/2 'super trimmed' brisket or untrimmed brisket and cut off most of the fat",
      '1 can of Rotel or diced tomatoes',
      '1 or more jalapenos',
      'Chicken broth',
      'Kosher salt',
      'Black pepper',
      'Tortillas',
      'Cotija cheese',
    ],
    steps: [
      'Rub brisket liberally with a 50/50 salt/pepper mixture.',
      'Cut brisket into chunks about 4 inch by 4 inch and place meat in crockpot with tomatoes and jalapeno(s).',
      'Pour chicken broth into crockpot until it is deep enough to cover almost everything (but leave 1-1.5 inches to the top of crockpot to avoid boiling over).',
      'Turn crockpot on to low and cook for a minimum of 12-15 hours. Once done, use tongs to pull meat chunks apart into strings and let cook for anouther 1-2 hours.',
      'Serve with tortillas and cotija cheese.',
    ],
    image: 'no-photo.png',
    course: 'crockpot',
    notes: '',
  },
  {
    name: "Grandma's Swedish Meatballs",
    id: '67',
    description: "Grandma's famous Swedish meatball recipe.",
    ingredients: [
      '1 pound ground beef',
      '1/4 pound ground pork',
      '1 1/2 Cups breadcrumbs',
      '1 Cup milk',
      '2 eggs',
      '1 medium onion, finely chopped',
      '1 1/2 tsp salt (or less)',
      '1/4 tsp allspice',
      '1/8 tsp nutmeg',
      '1/8 tsp cardamom',
      '1/8 tsp black pepper',
      '1 can (10 oz) beef broth',
      '1/2 Cup cream',
      '3/4 tsp dill',
      '3 Tbsp butter',
    ],
    steps: [
      'Mix all ingredients together except broth, cream, dill and butter.',
      'Shape into small balls and brown in butter in a pan. Add in the broth, cream, dill and butter. Cover and steam for 1 hour.',
    ],
    image: 'no-photo.png',
    course: 'main',
    notes:
      'Great over mashed potatoes or egg noodles. Grandma liked to substitute the cream for sour cream and chicken broth for beef broth.',
  },
  {
    name: 'Indian Spice Mix',
    id: '68',
    description: 'Simple mix of spices to use as a rub for chicken or whatever.',
    ingredients: [
      '2 Tbsp curry',
      '2 Tbsp cumin',
      '2 tsp turmeric',
      '2 tsp ground coriander',
      '1 tsp ground ginger',
      '1/2 tsp ground cardamom',
      '1/2 tsp ground cinnamon',
      'salt to taste (optional)',
    ],
    steps: ['Combine all ingredients in a small bowl and mix together.'],
    image: 'no-photo.png',
    course: 'seasonings',
    notes: '',
  },
  {
    name: 'Chicken Pot Pie Soup',
    id: '69',
    description: 'Soup that tastes just like chicken pot pie',
    ingredients: [
      '3 cups cauliflower florets',
      '3 cups chicken stock',
      '1 cup almond milk',
      '1 Tbsp olive oil',
      '1 onion, finely diced',
      '2 cloves garlic, crushed',
      '1 cup celery, diced',
      '1 cup carrots, diced',
      '1 tsp rosemary, chopped',
      '1 tsp thyme, chopped',
      '1/4 tsp salt',
      '1/2 tsp pepper',
      '1 cup peas or chopped green beans if doing Whole30',
      '2 chicken breats, cooked and shredded',
      '1 Tbsp chopped fresh parsley',
    ],
    steps: [
      'Place the cauliflower in a large pot on medium heat along with 1 cup chicken stock (you want enough stock to cover the cauliflower). Cover and steam the cauliflower until very tender. Transfer contents of the pot to a blender. Add the almond milk and 1 cup stock and blend until completely smooth. Set aside.',
      'Add the oil to the pot along with the garlic and onion and cook for about 4-5 minutes until the onion becomes translucent. Add the celery, carrots, rosemary, thyme, salt and pepper. Pour the rest of stock into the pot and simmer 8-10 minutes until the carrots become tender.',
      'Add in the peas/green beans, shredded chicken and cauliflower puree and cook for another 5 minutes until everything is warm. If the soup is too thick, add in more stock until it reaches desired consistency.',
      'Garnish with fresh parsley before serving.',
    ],
    image: 'no-photo.png',
    course: 'soups',
    notes: '',
  },
  {
    name: 'Cauliflower Stuffing',
    id: '70',
    description: 'A low-carb substition for a Thanksgiving stuffing.',
    ingredients: [
      '4 Tbsp butter',
      '1/2 medium onion, diced',
      '4 stalks celery, diced',
      '1 head cauliflower, cut into small florets',
      '1.5 cans mushrooms',
      '1 Tbsp sage',
      '1/4 Cup chicken broth',
      '1 1/2 Cup swiss cheese, cubed',
      '1/2 Cup slivered almonds',
    ],
    steps: [
      'Saute onions and celery in butter until soft.',
      'Combine all ingredients in an oven safe dish. Cook uncovered for 30 minutes at 350 degrees.',
      'Cover with tinfoil and cook another 10 minutes.',
    ],
    image: 'no-photo.png',
    course: 'sides',
    notes: '',
  },
  {
    name: 'Creamy Cauliflower Ham & Cheese Soup',
    id: '71',
    description: 'Great hearty soup, perfect for using up leftover Thanksgiving ham.',
    ingredients: [
      '2 Tbsp vegetable oil for cooking',
      '1 small yellow onion',
      '3/4 lb ham',
      '2 garlic cloves, pressed',
      '2 lb head of cauliflower',
      '1 1/2 Tbsp almond flour',
      '1 tsp dry sage',
      'Salt',
      'Fresh cracked black pepper',
      '3-4 Cups chicken stock',
      '1 bay leaf',
      '1/4 Cup heavy whipping cream',
      '4 oz sharp white cheddar cheese, grated',
    ],
    steps: [
      'Dice onion and set aside. Dice ham into small pieces and set aside. Cut cauliflower florets off, discard the stem, and chop florets into small pieces and set aside.',
      'Preheat medium pot over medium heat with some oil. Add diced onion and saute until transparent. Add ham and cook for a few minutes. Add pressed garlic, mix, and cook until fragrant.',
      'Add cauliflower, mix well and cook for a few minutes.',
      'Sprinkle flour over veggies and ham and mix well.',
      'Slowly pour in chicken stock while stirring so that it just covers the cauliflower mixture.',
      'Add bay leaf, salt, pepper and sage. Stir and cover with a lid, leaving a crack for steam to escape. Cook 20-25 minutes.',
      'Stir in whipping cream and cheese. Cook for a few more minutes and serve.',
    ],
    image: 'no-photo.png',
    course: 'soups',
    notes: '',
  },
  {
    name: 'Avocado Chicken Posole',
    id: '72',
    description: 'Low carb soup with flavorful broth.',
    ingredients: [
      '4 cups chicken stock',
      '2 lbs boneless, skinless chicken thight',
      '2 poblano peppers, sliced into large chunks',
      '1 avocado, cubed or sliced',
      '1 white onion, quartered',
      '2 cloves garlic, minced',
      '2 tsbp butter',
      '1 tbsp cumin',
      '1 tbsp oregano',
      '1 btsp pink Himalayan salt',
      '2 tsp chili powder',
      'fresh ground black pepper',
      'fresh cilantro for garnish',
    ],
    steps: [
      'Place all ingredients except avocado and cilantro into a crockpot or other slower cooker.',
      'Cook on low for 6-8 hours or until chicken is cooked through and contains no pink.',
      'Using a slotted sppon, remove and discard onion quarters and poblano pepper chunks.',
      'Remove chicken and shred in a separate bowl.',
      'Place shredded chicken back into slow cooker and cook for an additional 30 minutes.',
      'Ladle into serving bowls and garnish with avocado and cilantro.',
    ],
    image: 'no-photo.png',
    course: 'crockpot',
    notes: '',
  },
  {
    name: 'Lemon-Thyme Dressing',
    id: '73',
    description: 'Homemade Lemon-Thyme Dressing',
    ingredients: [
      '3 Tbsp freshly squeezed lemon juice',
      '1/2 Cup extra virgin olive oil',
      '2 Tbsp fresh thyme, finely chopped',
      '1 tsp salt',
      '1 tsp black pepper',
      '1 tsp lemon zest',
    ],
    steps: ['Whisk all ingredients in a small bowl or shake them in a jar and serve.'],
    image: 'no-photo.png',
    course: 'dressings',
    notes: '',
  },
  {
    name: 'Classic Balsamic Vinaigrette',
    id: '74',
    description: "It's salad dressing, yay!",
    ingredients: [
      '3 Tbsp balsamic vinegar',
      '1/2 Cup extra virgin olive oil',
      '1/2 tsp salt',
      '1/2 tsp black pepper',
    ],
    steps: ['Shake all ingredients in a jar and serve.'],
    image: 'no-photo.png',
    course: 'dressings',
    notes: '',
  },
  {
    name: 'Classic Lemon Vinaigrette',
    id: '75',
    description: "It's salad dressing, yay!",
    ingredients: [
      '3 Tbsp lemon juice',
      'Zest of 1/2 a lemon',
      '1/2 Cup extra virgin olive oil',
      '1/2 tsp salt',
      '1/2 tsp black pepper',
      '1 tsp honey',
    ],
    steps: ['Shake all ingredients in a jar or whisk in a small bowl and serve.'],
    image: 'no-photo.png',
    course: 'dressings',
    notes: '',
  },
  {
    name: 'Red Raspberry Vinaigrette',
    id: '76',
    description: "It's salad dressing, yay!",
    ingredients: [
      '3 Tbsp champagne vinegar',
      '1/2 Cup extra virgin olive oil',
      '1/2 Cup fresh raspberries mashed with a fork',
      '1 tsp sea salt',
      '1 tsp black pepper',
      '1 tsp honey',
    ],
    steps: ['Shake all ingredients in a jar or whisk in a small bowl and serve.'],
    image: 'no-photo.png',
    course: 'dressings',
    notes: '',
  },
  {
    name: 'Pecorino Romano & Black Pepper Vinaigrette',
    id: '77',
    description: "It's salad dressing, yay!",
    ingredients: [
      '1/4 Cup fresh lemon juice',
      '1/3 Cup olive oil',
      '1/2 Cup Pecorino Romano, freshly grated',
      '1 clove garlic, smashed for added flavor',
      '2 tsp balck pepper',
      '1/2 tsp salt',
    ],
    steps: ['Shake all ingredients in a jar or whisk in a small bowl and serve.'],
    image: 'no-photo.png',
    course: 'dressings',
    notes: '',
  },
  {
    name: 'Super Healthy Salad',
    id: '78',
    description: 'Just as the name says.',
    ingredients: [
      'Spinach',
      'Salmon, cooked to preference',
      'Walnuts',
      'Blueberries',
      'Beets',
      'Pomegranate',
      'Hemp seeds',
      'Ginger',
      'Avocado',
    ],
    steps: ['Put it all in a bowl or other container that can hold a salad.'],
    image: 'no-photo.png',
    course: 'salads',
    notes: '',
  },
  {
    name: 'Savory Butternut Squash',
    id: '79',
    description: 'A great winter side dish using the ingredients from Simon & Garfunkel\'s Scarborough Fair.',
    ingredients: [
      '1 butternut squash',
      '1/2 Tbsp onion powder',
      '1/2 Tbsp garlic powder',
      '1/2 Tbsp dried oregano',
      '1/2 Tbsp dried basil',
      '1/2 Tbsp parsley flakes',
      '1/2 Tbsp dried sage',
      '1/2 Tbsp dried rosemary',
      '1/2 Tbsp dried thyme',
      'Cooking spray',
      'Salt to taste',
    ],
    steps: ['Preheat oven to 425 degrees', 'Pierce the squash all over with a fork and place on a microwave-safe plate. Microwave on high for 2 minutes. Flip squash and microwave another 2 minutes. Flip again and microwave 1 1/2 minutes. Flip a final time and microwave 1 1/2 minutes. Let cool.', 'Using a vegetable peeler, peel the squash. Cut squash in half and scoop out fleshy middle. Cut into 3/4 inch cubes.', 'Line a baking sheet with aluminum foil and coat with cooking spray', 'Place squash pieces on baking sheet and sprinkle with spices and salt.', 'Place baking sheet in oven and cook for 20 minutes, checking for consistency, cooking longer if needed.'],
    image: 'no-photo.png',
    course: 'sides',
    notes: '',
  },
  {
    name: 'Molasses Crinkles',
    id: '80',
    description: 'Mom\'s famous molasses cookies.',
    ingredients: ['3/4 cup soft shortening or salted butter', '1 cup brown sugar', '1 egg', '1/4 cup molasses (not blackstrap)', '2 1/4 cups sifted flour', '2 tsp baking soda', '1/4 tsp salt (can omit if using salted butter)', '1/2 tsp cloves', '1 tsp cinnamon', '1 tsp ginger'],
    steps: ['Mix together shortening/butter, brown sugar egg and molasses.', 'Sift or stir together flour, baking soda, salt, cloves, cinnamon, ginger.', 'Add both mixtures together and chill the dough.', 'Preheat oven to 375 and grease cooking sheets.', 'Roll the dough into small round shapes the size of a large walnut or quarter.', 'Dip the tops of the round shapes in sugar and place on greased sheets sugar-side up.', 'Sprinkle each with a few drops of water.', 'Bake until set but not hard, 10-12 minutes.'],
    image: 'no-photo.png',
    course: 'desserts',
    notes: 'Make about 4 dozen.',
  },
  {
    name: 'Susie\'s Meatloaf',
    id: '81',
    description: 'Susie\'s meatloaf or one big meatball.',
    ingredients: ['1 lb ground chuck', '1/4 lb ground pork', '1/2 yellow onion', '1 cup Romano (1.5 for 3 lbs)', '2 eggs per lb of meat', '1 cup breadcrumbs (1.5 for 3 lbs)', '1/2 cup parsley (for 3 lbs)', 'pepper', 'salt', 'sugar', 'carrots', 'potatoes'],
    steps: ['Preheat overn to 350 degrees.', 'Mix all ingredients together except potatoes and carrots.', 'Place carrots and potatoes at the bottom of a baking pan and place meatloaf on top.', 'Cook for 45 minutes and continue to cook and check until 160 degrees.'],
    image: 'no-photo.png',
    course: 'main',
    notes: '',
  },
  {
    name: 'Mom\'s Meatballs',
    id: '82',
    description: 'A variation on my wife Susie\'s meatballs which I\'ll get around to adding eventually.',
    ingredients: [
      '2 eggs',
      '1/2 cup seasoned breadcrumbs',
      '1/2 cup parmesan cheese',
      '1/2 cup chopped onion',
    ],
    steps: [
      'Preheat oven to 350 degrees.',
      'Mix all ingredients, form into balls, and bake 25-30 minutes.',
    ],
    image: 'no-photo.png',
    course: 'main',
    notes: 'All ingredients are per 1 pound of meat, using 2/3 ground chuck and 1/3 ground pork.',
  },
  {
    name: 'Susie\'s Pumpkin Pie',
    id: '83',
    description: 'The very best pumpkin pie on Earth.',
    ingredients: [
      '2/3 cup brown sugar',
      '2 tbsp flour',
      '1/2 tsp salt',
      '2 tsp pumpkin pie spice',
      '1 1/2 cups cannd solid pack pumpkin',
      '4 tbsp maple syrup',
      '3 large eggs',
      '1 cup whipping cream',
      '1 purchased frozen 9-inch pie crust',
    ],
    steps: [
      'Place baking sheet in oven and preheat to 450 degrees.',
      'Whisk first 8 ingredients together in large bowl to blend. Whisk in pumpkin, molasses and eggs then cream. Pour mixture into prepared crust.',
      'Place pie on preheated baking sheet in oven. Bake 10 minutes. Reduce heat to 325 degrees and bake until sides puff and center is just set, about 40 minutes. Remove pie and cool.',
    ],
    image: 'no-photo.png',
    course: 'desserts',
    notes: 'Uncooked pie can be made a day ahead of time, covered, and refrigerated.',
  },
  {
    name: 'Oven Baked Steak Fries',
    id: '84',
    description: 'The best and easiest homemade fries.',
    ingredients: [
      'Baking potatoes (any amount you want',
      'Butter',
      'Salt and pepper to taste',
    ],
    steps: [
      'Preheat oven to 400 degrees.',
      'Wash and slice potatoes into circles about 1-1 1/2cm thick.',
      'Melt enough butter to coat a baking sheet. Dip potato slices in the melted butter and arrange on baking sheet.',
      'Sprinkle on salt and pepper.',
      'Bake in oven until desired crispness, about 45 minutes, flipping halfway through.',
    ],
    image: 'no-photo.png',
    course: 'sides',
    notes: '',
  },
  {
    name: 'Slow Cooker Butter Chicken',
    id: '85',
    description: 'An easy way to make butter chicken.',
    ingredients: [
      '1 pound boneless, skinless chicken breast (or thighs)',
      '1 medium onion, diced',
      '2 tsp coconut oil',
      '4 cloves garlic, finely minced',
      '1 tsp fresh ginger, finely minced',
      '1 tsp coriander',
      '1 tsp cumin',
      '1 tsp cardamom',
      '1/2 tsp salt',
      '1/4-1/2 tsp cayenne pepper (optional)',
      '1 14-oz can coconut milk (full fat)',
      '1 6-oz can tomato paste',
      'Juice of 1 lime',
      '1/4 cup cilantro or to taste',
    ],
    steps: [
      'In a medium saucepan, heat coconut oil over medium heat. Add onion and saute until translucent and fairly tender. Add garlic, ginger, spices and salt and cook 1 more minute until all spices are fragrant.',
      'Stir in coconut milk and tomato paste and stir until well combined.',
      'Add chicken to slow cooker and pour the sauce over it. Cook on high heat for 3-4 hours or low heat for 6-8 hours.',
      'Remove chicken pieces and shred or dice, putting them back in the pot when done. Squeeze in lime juice, top with cilantro and serve with naan or over vegetables or rice.',
    ],
    image: 'no-photo.png',
    course: 'crockpot',
    notes: '',
  },
  {
    name: 'Broccoli Supreme',
    id: '86',
    description: 'A Strzelec Thanksgiving staple.',
    ingredients: [
      '1/2 cup long grain rice, cooked and drained',
      '2 boxes (or 1 bag) frozen broccoli',
      '1 can water chestnuts, drained',
      '1 8-oz jar Cheez Whiz (or similar product)',
      '1 can cream of chicken soup',
      'Butter',
    ],
    steps: [
      'Preheat oven to 350 degrees.',
      'Generously butter a large casserole dish.',
      'Layer the dish with broccoli, water chestnuts, rice then Cheez Whiz. Bake 30-40 minutes until a light brown crust forms.',
    ],
    image: 'no-photo.png',
    course: 'sides',
    notes: '',
  },
  {
    name: 'Mom\'s Turkey Stuffing',
    id: '87',
    description: 'Another Strzelec Thanksgiving staple.',
    ingredients: [
      '4 tbsp butter',
      '1/2 medium onion, diced',
      '3 celery stalks, diced',
      '1 package onion and sage bread stuffing',
      '1 egg, beaten',
      '1 can of mushrooms, drained',
      '1 1/2 cups chicken broth',
      '1 cup swiss cheese, cubed',
      '1/2 cup slivered almonds',
    ],
    steps: [
      'Saute onions and celery in butter until softened.',
      'Combine all ingredienst in a bowl.',
      'Place mixture in an oven-safe dish and cook at 350 degrees for 30-40 minutes.',
      'Additional broth can be added while the stuffing is cooking to retain enough moisture.',
    ],
    image: 'no-photo.png',
    course: 'sides',
    notes: 'This dish can also use cauliflower instead of bread stuffing for a low carb option.',
  },
];
